/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import java.io.IOException;
import restaurante.Restaurante;
import restaurante.XmlParser;


/**
 *
 * @author Fabrizio
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    
    
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws IOException, ClassNotFoundException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
        Restaurante rediPicsa=Restaurante.getInstance();
//        rediPicsa.AgregarPlatillo("ENT-008", "CHORIZO!!!!!", 900, 6969.69f, 1000, "Picha");
//        rediPicsa.AgregarPlatillo("ENT-009", "CHORIZO!!!!!", 900, 6969.69f, 1000, "Pichota");
//        rediPicsa.AgregarPlatillo("ENT-010", "CHORIZO!!!!!", 900, 6969.69f, 1000, "Pichin");
//        rediPicsa.AgregarPlatillo("PRN-008", "CHORIZO!!!!!", 900, 6969.69f, 1000, "Picha");
//        rediPicsa.AgregarPlatillo("PRN-010", "CHORIZO!!!!!", 900, 6969.69f, 1000, "Pichota");
//        rediPicsa.AgregarPlatillo("PRN-009", "CHORIZO!!!!!", 900, 6969.69f, 1000, "Pichin");
//        rediPicsa.AgregarPlatillo("BEB-009", "CHORIZO!!!!!", 900, 6969.69f, 1000, "Picha");
//        rediPicsa.AgregarPlatillo("BEB-008", "CHORIZO!!!!!", 900, 6969.69f, 1000, "Pichota");
//        rediPicsa.AgregarPlatillo("BEB-010", "CHORIZO!!!!!", 900, 6969.69f, 1000, "Pichin");
//        rediPicsa.AgregarPlatillo("PTR-009", "CHORIZO!!!!!", 900, 6969.69f, 1000, "Picha");
//        rediPicsa.AgregarPlatillo("PTR-010", "CHORIZO!!!!!", 900, 6969.69f, 1000, "Pichota");
//        rediPicsa.AgregarPlatillo("PTR-008", "CHORIZO!!!!!", 900, 6969.69f, 1000, "Pichin");
        XmlParser parser=new XmlParser();
        //parser.CrearXML(rediPicsa.getMenu());
        parser.CargarXML(rediPicsa.getMenu(),rediPicsa);
        Servidor server=new Servidor();
        server.iniciarServidor();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
